### ISSUE TITLE
Error api/send

### ISSUE THREAD

**Issue by joseserrano15** [leifermendez/bot-whatsapp#101]
Hola, tengo un error al intentar enviar un mensaje a la ruta api/send con postman. ¿Cómo podría solucionarlo?

Gracias.

![image](https://user-images.githubusercontent.com/68348356/192558983-61eae3b2-8332-4ac2-b4ec-f72cd9a27782.png)

**Comment by KJoaquin** [comment]
Como lo estas consumiendo en postman??

**Comment by joseserrano15** [comment]
Así: 
![image](https://user-images.githubusercontent.com/68348356/192650890-231e5974-d04a-4cb3-9cf4-13aa652afe6b.png)

**Comment by joseserrano15** [comment]
Gracias, con apoyo de otro colega logré solucionarlo.
