### ISSUE TITLE
Hola tengo un problema ejecuto el proyecto me sale client ready pero no lee los mensajes

### ISSUE THREAD

**Issue by Jvrmmora** [leifermendez/bot-whatsapp#104]
Se ejecuta correctamente el proyecto, se autentica correctamente con el QR pero al escribir hola para hacer funcionar el bot no me funciona

**Comment by maquinate2** [comment]
hola a mi tambien me esta sucediendo lo mismo,

**Comment by RiWAR** [comment]
> hola a mi tambien me esta sucediendo lo mismo,

igual  a mi, hasta los q ya tenia corriendo

**Comment by trakkiesed** [comment]
Solo actualiza y funciona "npm i whatsapp-web.js"

**Comment by maquinate2** [comment]
es correcto, ya liberaron la version 1.18.0 la cual funciona con la version 
 WhatsApp Web version  v2.2240.7
