### ISSUE TITLE
Problema con DiaglogFlow

### ISSUE THREAD

**Issue by danielruiz1094** [leifermendez/bot-whatsapp#106]
Al ejecutar el bot funciona con normalidad, pero al querer hacerlo con diaglogFlow sale el siguiente error.

C:\Users\soporte-jr\Desktop\bot-whatsapp\adapter\diaglogflow.js:59
    const customPayload = parsePayload['payload']
                                      ^

TypeError: Cannot read properties of undefined (reading 'payload')
    at detectIntent (C:\Users\soporte-jr\Desktop\bot-whatsapp\adapter\diaglogflow.js:59:39)

Node.js v18.10.0

**Comment by KJoaquin** [comment]
Solo tienes que comentar esa linea si no estas utilizando esa función, ya que no esta leyendo ese objeto.

**Comment by leifermendez** [comment]
Fix
