### ISSUE TITLE
implementarlo en node-red en raspberry

### ISSUE THREAD

**Issue by spereg53** [leifermendez/bot-whatsapp#12]
buenas tardes,me podrias apoyar para implementarlo en node-red,instale el whatsappbot para node-red, y me sale este error:Error while starting Whatsapp client "session": Failed to launch the browser process!
/home/pi/.node-red/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: 22: Syntax error: "(" unexpected

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
gracias por el apoyo

**Comment by leifermendez** [comment]
Hola te dejo la documentación para instalar el Linux 
https://github.com/leifermendez/bot-whatsapp/wiki/Instalaci%C3%B3n
