### ISSUE TITLE
Botones

### ISSUE THREAD

**Issue by Aronchavez** [leifermendez/bot-whatsapp#124]
Alguien pudo activar los botones, lo del multidispositivo ya no se puede desactivar de parte de WhatsApp lograron activarlos si me puede ayudar

**Comment by juan-silveira** [comment]
Como activar los botones? Estoy solo con uno dispositivo y no funciona.

**Comment by KJoaquin** [comment]
npm i github:pedroslopez/whatsapp-web.js#fix-buttons-list

**Comment by leifermendez** [comment]
Exactamente como dice @KJoaquin
