### ISSUE TITLE
Error al leer el codigo QR

### ISSUE THREAD

**Issue by fergolive** [leifermendez/bot-whatsapp#13]
Error de whatsapp-web.js
Cannot read properties of undefined (reading 'Socket')

https://github.com/pedroslopez/whatsapp-web.js/pull/1241

**Comment by leifermendez** [comment]
@fergolive ayer actualice las librerías puedes y se tiene la versión más reciente de whatsapp-web puedes revisar aquí 
https://github.com/leifermendez/bot-whatsapp/commit/d200100caafe4870ee7d7eb0c718171b7a1d80fd#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by leifermendez** [comment]
Déjame saber si funciono

**Comment by landito82** [comment]
¿Alguna guía para hacer el downdate a WhatsApp single device o la manera tradicional?
