### ISSUE TITLE
Crashea al recibir imagen sin texto (Dialogflow)

### ISSUE THREAD

**Issue by Maxjose** [leifermendez/bot-whatsapp#15]
** Archivo Media Guardado **
C:\Users\Usuario\Desktop\bot\node_modules\@grpc\grpc-js\build\src\call.js:31
    return Object.assign(new Error(message), status);
                         ^

Error: 3 INVALID_ARGUMENT: Input text not set.
    at Object.callErrorFromStatus (C:\Users\Usuario\Desktop\bot\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (C:\Users\Usuario\Desktop\bot\node_modules\@grpc\grpc-js\build\src\client.js:180:52)
    at Object.onReceiveStatus (C:\Users\Usuario\Desktop\bot\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:365:141)
    at Object.onReceiveStatus (C:\Users\Usuario\Desktop\bot\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:328:181)
    at C:\Users\Usuario\Desktop\bot\node_modules\@grpc\grpc-js\build\src\call-stream.js:182:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 3,
  details: 'Input text not set.',
  metadata: Metadata {
    internalRepr: Map(1) {
      'grpc-server-stats-bin' => [
        Buffer(10) [Uint8Array] [
          0, 0, 87, 70, 32,
          0, 0,  0,  0,  0
        ]
      ]
    },
    options: {}
  },
  note: 'Exception occurred in retry method that was not classified as transient'
}

**Comment by Maxjose** [comment]
Al parecer no hay solución para esto.

**Comment by leifermendez** [comment]
@Maxjose buenas recien lo probe no me presenta error pudieras decir si es una imagen con un formato especifico te recomiendo tener la version actualizada
https://github.com/leifermendez/bot-whatsapp/wiki/Como-Actualizar-a-mi-%C3%BAltima-versi%C3%B3n

**Comment by Maxjose** [comment]
El problema se presenta al recibir una imagen regular, no estoy hablando de archivos en particular.
Al principio de de las líneas se puede ver que el bot efectivamente guarda la imagen.
Es importante aclarar que eso me pasa cuando estoy usando **Dialogflow** únicamente, según el poco conocimiento que tengo del tema el error es **"3 INVALID_ARGUMENT: Input text not set."** como lo indica la misma consola.

Con respecto a lo que me comentas, la prueba la hice el mismo día que realice el post **(07/03/22)** es decir que no es tanto tiempo.
De igual manera voy a volver a probar para salir de duda.

**Gracias por responder.**

**Comment by satara2358** [comment]
Gracias MaxJose, en mi caso se cierra el bot al recibir una nota de voz usando Dialogflow. Me dicen que hay que crear una rutina para que capture esos eventos pero no lo he podido solucionar ...

**Comment by Maxjose** [comment]
Exactamente es lo mismo que pasa al recibir una imagen, como no se mucho de programación no he encontrado una solución al problema :/

**Comment by leifermendez** [comment]
Solucionando esperen en el transcurso del día el Update

**Comment by Maxjose** [comment]
> Solucionando esperen en el transcurso del día el Update

Gracias hombre!
