### ISSUE TITLE
Problema con el ChatBot

### ISSUE THREAD

**Issue by jruiz72** [leifermendez/bot-whatsapp#160]
Hola Leifer, saludos desde Bogotá

Te escribo porque he intentado utilizar el ChatBot de Whatsapp pero no me responde. Es decir, me aparece en la consola de Visual:
🔴 escribe: hola
BODY *lo que escribí*
Saved

Pero el chat bot no responde nada. Seguramente cometí algún error pero no sé cómo solucionarlo.

De antemano muchas gracias.

**Comment by leifermendez** [comment]
Hola @jruiz72 https://github.com/leifermendez/bot-whatsapp/blob/dev/CONTRIBUTING.md puedes guiarte de esta rama

**Comment by jruiz72** [comment]
Super, muchas gracias Leifer!
