### ISSUE TITLE
Chat-bot Estados de WhatsApp en consola

### ISSUE THREAD

**Issue by AlexSenju** [leifermendez/bot-whatsapp#17]
Después de hacer la conexión con WhatsApp, se muestra en consola todos los estados de mis contactos.

![image](https://user-images.githubusercontent.com/101194932/157258868-bfe59963-52e5-43db-8299-73086f8f46b1.png)

**Comment by leifermendez** [comment]
@AlexSenju buenas eso deberia de evitarse con esta condicion https://github.com/leifermendez/bot-whatsapp/blob/main/app.js#L50 de igual manera si me confirmas o puedes hacer un pull request con la mejora seria genial
