### ISSUE TITLE
Sesiones con multidevice 

### ISSUE THREAD

**Issue by tonyvazgar** [leifermendez/bot-whatsapp#18]
Hola, estuve investigando y con la nueva version de WA ya no se puede guardar la sesión por culpa de lo de multidispositivos, [https://github.com/pedroslopez/whatsapp-web.js/issues/1292#issuecomment-1059706855](url) 

Ahora siempre que hago cambios en mis archivos para probar tengo que leerlo siempre porque no guarda el session.json, espero puedas ayudarnos porque apenas estoy entendiendole a node

**Comment by eduande** [comment]
Hola, tengo problemas para la conexión también, aparentemente la última actualización de whatsapp afecto, no logro conectarlo. Capaz es algo sencillo.

**Comment by holmansneyderc** [comment]
Tengo el mismo problema

**Comment by eduande** [comment]
Amigo @holmansneyderc eso ya está resuelto, descárgate el actualizado

**Comment by leifermendez** [comment]
Buenas dejo guía explicando aquí https://github.com/leifermendez/bot-whatsapp/wiki
