### ISSUE TITLE
Ejecutando en Windows 10, Anduvo, pero ya no arranca aunque lo reinstale (?)

### ISSUE THREAD

**Issue by barabasj** [leifermendez/bot-whatsapp#19]
Ayer comencé a probar este bot y funcionó OK (excepto al arrancar el cliente Windows de WhatsApp, que en general terminaba corrompiendo algo y solo se solucionaba reinstalando). Hoy intento ejecutarlo nuevamente y recibo
![Captura-error-bot](https://user-images.githubusercontent.com/12459930/157556983-f8b0c68a-f104-40be-94d4-a1fc84875515.JPG)
Alguna idea?
Gracias, Javier.

**Comment by barabasj** [comment]
Este error sucede al intentar validar el QR con la cuenta de WhatsApp. Reinstalar no resuelve tampoco.

**Comment by Jvrmmora** [comment]
Tengo el mismo error :/

**Comment by eduande** [comment]
Aparentemente whatsapp se actualizó en las últimas horas, ahora no funciona el bot, capaz es sencillo para solucionar @leifermendez, muchas gracias

**Comment by Gamosky** [comment]
En la mañana hacia unas pruebas y de repente empezo con ese error, ojala el amigo leifer nos de una pronta solucion con sus grandes conocimientos y nos ilumine el camino saludos estamos al pendiente

**Comment by leifermendez** [comment]
https://github.com/leifermendez/bot-whatsapp/wiki/Como-Actualizar-a-mi-%C3%BAltima-versi%C3%B3n
Ya actualice pueden ver la explicación aquí

**Comment by barabasj** [comment]
Genial! Ha vuelto a la vida. Gracias!
