### ISSUE TITLE
Problema, EXCEL

### ISSUE THREAD

**Issue by jv-gitb** [leifermendez/bot-whatsapp#2]
Hola tengo un problema, cuando guarda un chat guarda el mensaje que envía el Bot y no el que recibe, si alguien sabe la solución

**Comment by leifermendez** [comment]
@jv-gitb me podrías compartir un captura o una manera de replicar el problema

**Comment by jv-gitb** [comment]
Descargue el zip otra vez por si cambie algo y por eso daba ese problema pero sigue igual
![image](https://user-images.githubusercontent.com/99473878/153574184-5532ae78-30f2-4dc3-b846-29a0c6acbce5.png)

**Comment by jv-gitb** [comment]
@leifermendez he probado cambiando varias cosas pero no encuentro la solucion, tambien pasa cuando guarda el chat cuando utilizo DialogFlow
