### ISSUE TITLE
esta version de codigo no toma los parametros enviados por un intents de dialogflow, aguna solucion ? muchas gracias!!

### ISSUE THREAD

**Issue by maquinate2** [leifermendez/bot-whatsapp#20]

**Comment by maquinate2** [comment]
hola muchas gracias por responder, te cuento tengo  un intents con el cual recepciono los siguientes parametros, email,nombre,apellido, los 3 son requeridos, una vez efectuada la carga los envio por fultfillme el cual tengo direccionado a un whebooks en node.js, quien se encarga de guardarlo en una base de datos mysql, al probarlo desde dialogflow  recoje y guarda los datos de los parametros en la base de datos, en cambio cuando intento hacerlo por el whataspp,  al terminar e cargar el primer parametro  en lugar de pasar al segundo parametro directamente me manda al Default Fallback Intent, es como que no reconociera lo que el intents esta enviando o queriendo realizar,  la verdad estoy medio desorientado si me podrias orientar te lo agradeceria,  nuevamente te doy las gracias por responder mi inquietud, aguardo tus comentarios!!

**Comment by maquinate2** [comment]
hola otro tema, veo que actualizaste la libreria de whatsapp, pero el codigo no soporte multi divece, te paso el error, puerde ser ?

Ver QR http://localhost:3000/qr
C:\maquinate\proyectobotelectrogenius\bot 05032022\10-03-2022\bot-whatsapp\node_modules\whatsapp-web.js\src\authStrategies\LegacySessionAuth.js:57
        if(isMD) throw new Error('Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.');
                       ^

**Comment by leifermendez** [comment]
Buenas @maquinate2 con respecto a el ultimo issue https://github.com/leifermendez/bot-whatsapp/wiki

**Comment by leifermendez** [comment]
Con respecto al tema del dialog flow por ahora no funciona con contexto fluidos solo con las principales intenciones espero pronto actualizar y agregarle nuevas funcionalidades

**Comment by Gonzalito87** [comment]
para resolver este inconveniente yo tuve que realizar lo siguiente: 
 - dirígete hacia la carpeta donde tengas el proyecto y luego a la carpeta adapter
 - dentro de la carpeta adapter buscar el archivo dialogflow.js y editalo
 - Comentar la linea //const nanoid = require('nanoid')
 - Cambiar el parámetro de la const sessionId = 1

**Comment by Gonzalito87** [comment]
> para resolver este inconveniente yo tuve que realizar lo siguiente:
> 
> * dirígete hacia la carpeta donde tengas el proyecto y luego a la carpeta adapter
> * dentro de la carpeta adapter buscar el archivo dialogflow.js y editalo
> * Comentar la linea //const nanoid = require('nanoid')
> * Cambiar el parámetro de la const sessionId = 1

el problema estaba por que nanoid por cada interacción con nuestro webhook nos generaba un nuevo id por cada mensaje que enviamos, estoy seguro que este solución pueda llegar a tener inconvenientes pero ya hice varios intentos y pruebas y hasta ahora no encontre inconvenientes, seguramente el código se pueda mejorar en la parte del ID y su session pero por ahora es la única solución que pude ingeniar

**Comment by hunimato** [comment]
Mil gracias @Gonzalito87, me funciono !

Gracias,

Hugo

**Comment by leifermendez** [comment]
Solucionado en la nueva PR
