### ISSUE TITLE
Error recibiendo mensajes correctos de "ciertos" usuarios.

### ISSUE THREAD

**Issue by barabasj** [leifermendez/bot-whatsapp#21]
El bot está funcionando ok, pero con un usuario de los que están probándolo, al enviar un simple Hola, por ejemplo, recibe parte del mensaje desde el bot y el servicio cancela con el siguiente mensaje...
![Bot-error](https://user-images.githubusercontent.com/12459930/157779306-b168b144-1bfa-4b4c-8b73-11b357adc8e2.JPG)
Alguna idea???
Muchas gracias, Javier.

**Comment by Arthurlink06** [comment]
Es un problema de la dependencia encargada de poner las conversaciones en excel. 
![image](https://user-images.githubusercontent.com/64654183/157887572-33ac265e-73fb-470d-87dc-5c960d837739.png)

**Comment by leifermendez** [comment]
Espero esta semana cambiar la librería de excel y hacerlo algo más tradicional un json o algo

**Comment by barabasj** [comment]
Gracias por tu respuesta. El tema que me resulta extraño es el porqué no sucede con todos los usuarios..... si envían el mismo mensaje.... Javier.

**Comment by barabasj** [comment]
Leifer... el problema sigue igual para mi. Adjunto el output del error... será el mismo?
![image](https://user-images.githubusercontent.com/12459930/158388982-881f7d4c-49b9-462a-b208-ff8f415e97d6.png)
Espero tus comentarios. Gracias maestro!

**Comment by leifermendez** [comment]
@barabasj pero seguiste los pasos https://github.com/leifermendez/bot-whatsapp/wiki/Como-Actualizar-a-mi-%C3%BAltima-versi%C3%B3n
No debería tener error porque básicamente la librería de excel se elimino
