### ISSUE TITLE
Error al vincular dispositivo cuando se escanea el codigo QR

### ISSUE THREAD

**Issue by holmansneyderc** [leifermendez/bot-whatsapp#22]
En la version actual no permite iniciar sesión cuando escaneo el QR,

 client.on('authenticated', (session) => {
 session is undefined

**Comment by tonyvazgar** [comment]
> Asegurate de no estar en la versión Multi-Device y de tener actualizado el proyecto
> https://github.com/leifermendez/bot-whatsapp/wiki/Como-Actualizar-a-mi-%C3%BAltima-versi%C3%B3n

Sabes como salirte de la version multidevice? Tengo iPhone y no la encuentro por ningún lado :(
Se me activó solito el multi device :(

**Comment by leifermendez** [comment]
Ya tenemos soporte para multi-device dejo una guia explicando cosas
https://github.com/leifermendez/bot-whatsapp/wiki
