### ISSUE TITLE
Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts

### ISSUE THREAD

**Issue by ShiomeDiaz** [leifermendez/bot-whatsapp#23]
Alguna solución al problema? 
ya actualice el repo pero se sigue presentando, hace unas 8 horas funcionaba bien con whatsapp business, pues con el whatsapp normal solo me daba el mismo error.
me pueden ayudar  porfa 👍
![sserror](https://user-images.githubusercontent.com/49491301/158039933-d9823925-15dc-4cac-ab65-d3e7c3b58ead.png)

**Comment by leifermendez** [comment]
Hola tienes activo el modo multi device en tu cuenta de WhatsApp?

**Comment by leifermendez** [comment]
https://github.com/leifermendez/bot-whatsapp#atencion-1-

**Comment by ShiomeDiaz** [comment]
para ser sincero no active el modo beta, al parecer seria por error o fue automático,  sabes de alguna manera para salir del beta? he estado investigando el como pero hasta el momento no lo he podido saber.

**Comment by Gamosky** [comment]
> para ser sincero no activo el modo beta, al parecer seria por error o fue automático, ¿sabes de alguna manera para salir del beta? he estado investigando el como pero hasta el momento no lo he podido saber.

Hola amigo, no se si te ayude mi aportacion para salir del modo beta del whatsapp lo haces desde la misma aplicacion la abres,  vas a la parte de vincular dispositivo si tienes activado la version beta debe decirte(version beta para varios dispositivos) basta con presionar ese boton y te va abrir una nueva ventana y ahi en la parte  de abajo dice salir de la version beta

**Comment by tonyvazgar** [comment]
> para ser sincero no active el modo beta, al parecer seria por error o fue automático, sabes de alguna manera para salir del beta? he estado investigando el como pero hasta el momento no lo he podido saber.

![IMG_7813](https://user-images.githubusercontent.com/21047090/158219939-8fae5c44-4e61-465d-b2ac-7a12263763e7.PNG)
![IMG_7814](https://user-images.githubusercontent.com/21047090/158219946-1f000d2c-d0e9-4a1d-96a8-72f21dcd0253.PNG)

A mi no me deja salirme, ya no veo la opción ni en business ni en WA normal :(

**Comment by ShiomeDiaz** [comment]
a mi tampoco me aparece la opcion, tuve que crear otra cuenta.

**Comment by leifermendez** [comment]
Hola ya se esta trabajando pueden ir probando el proyecto desde esta rama https://github.com/leifermendez/bot-whatsapp/tree/multidevice

**Comment by leifermendez** [comment]
https://github.com/leifermendez/bot-whatsapp/blob/main/.env.example#L12 en la ultima versión publicada ya se acepta multidevice solo debes de cambiar el boolean en los enviroments
