### ISSUE TITLE
Problemas con Dialogflow

### ISSUE THREAD

**Issue by Nix0n98** [leifermendez/bot-whatsapp#26]
Hola @leifermendez tengo un problema. A la hora de colocar en el archivo .env.example el parámetro para usar dialogflow y cuando quiero usarlo, en consola me sale el error : 

BODY: "palabra que escribo en WhatsApp" 
{ lastStep: null } 

Tengo bien las conexiones, coloqué muy bien y cuidadosamente los datos en chatbot-account.json pero sigue sin funcionar. 

Te agradezco una ayudita, muchas gracias.

**Comment by leifermendez** [comment]
Buenas recuerda debes crear un archivo __.env__ con las variables que estan en el de ejmeplo

**Comment by Nix0n98** [comment]
Solucionado. Muchas gracias! @leifermendez
