### ISSUE TITLE
corrup zip ?

### ISSUE THREAD

**Issue by ShiomeDiaz** [leifermendez/bot-whatsapp#27]
hola @leifermendez  haciendo test a la app me he encontrado con este error  he tratado de hacer un mejor seguimiento pero no le he dado con el chiste, sabes alguna razón o solución?  me gustaria saber que piensas sobre el error. al principio pensaba que era por el flujo de chats "solo eran dos", luego pense que eran las imagenes o algo asi pero no lo son.
![error bot](https://user-images.githubusercontent.com/49491301/158290188-e4611971-3b1c-49c1-8c2d-1d102c69d369.PNG)

**Comment by ShiomeDiaz** [comment]
me acabo de dar cuenta que si le envio al bot una imagen sale el mismo error.

**Comment by leifermendez** [comment]
@ShiomeDiaz problema solucionado en la ultima update, se removio lo de excel y ahora se tiene otro motor de gestion.
te invito a pasarte por la guia de como actualizar
https://github.com/leifermendez/bot-whatsapp/wiki/Como-Actualizar-a-mi-%C3%BAltima-versi%C3%B3n
