### ISSUE TITLE
Error recibiendo mensajes correctos de "ciertos" usuarios. (continúa)

### ISSUE THREAD

**Issue by barabasj** [leifermendez/bot-whatsapp#29]
Leifer, el error sigue para mi. Será el mismo? (adjunto output del error)
![image](https://user-images.githubusercontent.com/12459930/158389315-531371a5-fa45-4e0b-92e6-45402434a7fa.png)
Espero tus comentarios.... gracias maestro!

**Comment by barabasj** [comment]
Lo actualicé según tu procedimiento.... el error que adjunto es el mismo????

**Comment by barabasj** [comment]
Mi instalación parece seguir usando Excel.... no se habrá actualizado..... que extraño... lo instalaré de nuevo de cero.

**Comment by leifermendez** [comment]
Lo reviso nuevamente igual revisa si esta funcion la tienes igual https://github.com/leifermendez/bot-whatsapp/blob/main/controllers/send.js#L96

**Comment by barabasj** [comment]
Me parece que sigue siendo la anterior..... voy a re-instalar todo de cero nuevamente. Te cuento luego. Gracias!

**Comment by barabasj** [comment]
Ahora salva json en lugar de excel... antes no se había actualizado correctamente.. hago que mis testers lo prueben. Gracias!!!!

**Comment by leifermendez** [comment]
Genial muchas gracias recuerda que cualquier aporte puedes hacer un Pull Request
