### ISSUE TITLE
Hola @leifermendez, probando la nueva actualizacion los botones no estan funcionando. es esto correcto?

### ISSUE THREAD

**Issue by ShiomeDiaz** [leifermendez/bot-whatsapp#31]

**Comment by ShiomeDiaz** [comment]
@leifermendez he hecho varias pruebas pero sigue sin funcionar.

**Comment by ShiomeDiaz** [comment]
El disparador al parecer tampoco esta funcionando.

**Comment by Arthurlink06** [comment]
Amigo, date cuenta de los cambios constantes que tiene el proyecto, ahora ya no se utiliza los excel, se utiliza un archivo Json para guardar los chats , mira en [aquí](https://github.com/leifermendez/bot-whatsapp/commits/main)  para que veas las actualizaciones que se han hecho.

**Comment by sucoabedrabbo** [comment]
Hola yo sigo con el mismo problema tengo montado en Heroku he actualizado todos los archivos, algún comentario..??

**Comment by leifermendez** [comment]
Buenas actualmente con la version MultiDevice no esta funcionando los botones espero pronto tener update
