### ISSUE TITLE
Api, Mensaje Enviado Pero no Se envia

### ISSUE THREAD

**Issue by izelaya051290** [leifermendez/bot-whatsapp#33]
![image](https://user-images.githubusercontent.com/66973501/159049273-399f79c2-36b6-45bf-8d46-4ef0fda1be9d.png)
 
Un saludo Leifer, gracias por los aportes, sos un crack, te escribo ya que tengo este inconveniente donde mando el msje desde postman, y me tira de exitoso, pero sale del whatsapp

y en consola me tira esto
![image](https://user-images.githubusercontent.com/66973501/159049539-e72b1830-2ac6-4b19-aee6-ba8a9a765fdc.png)

**Comment by leifermendez** [comment]
Hola gracias por escribir en tu postsmn al lado de donde dice GrahpQl dice text cambialo por Json

**Comment by izelaya051290** [comment]
Gracias por la pronta respuesta, me ahora que replace.number no es una funcion

![image](https://user-images.githubusercontent.com/66973501/159052933-0cfb60d8-b0e0-4dca-b624-5e7df393bf9e.png)

TEngo el Multidiveice en TRUE

**Comment by izelaya051290** [comment]
Muchas Gracias @leifermendez resuelto
