### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by Huguitis** [leifermendez/bot-whatsapp#36]
![image](https://user-images.githubusercontent.com/65133800/160006983-e66e24de-a465-41a2-a72c-b1b1db6dee80.png)

**Comment by leifermendez** [comment]
@Huguitis pasate por estos videos donde indico como lo necesario para instalar en linux https://github.com/leifermendez/bot-whatsapp/wiki/Instalaci%C3%B3n

**Comment by Huguitis** [comment]
> @Huguitis pasate por estos videos donde indico como lo necesario para instalar en linux https://github.com/leifermendez/bot-whatsapp/wiki/Instalaci%C3%B3n

thanks
