### ISSUE TITLE
No me responde los msj

### ISSUE THREAD

**Issue by facu-rai** [leifermendez/bot-whatsapp#37]
Hola leifer, soy facundo, te hable por youtube, aca te dejo el programa para que lo veas
[README.md](https://github.com/leifermendez/bot-whatsapp/files/8351076/README.md)
[CHANGELOG.md](https://github.com/leifermendez/bot-whatsapp/files/8351081/CHANGELOG.md)
no me deja subir otros archivos como hago?

**Comment by hunimato** [comment]
Hola, no se ve ningun error como para poder ayudarte, puedes describirlo?

**Comment by leifermendez** [comment]
@facu-rai buenas podrias pasarme una captura o video para poder tener mas contexto del error
