### ISSUE TITLE
Guardar Sesión - undefined

### ISSUE THREAD

**Issue by fenixbinario** [leifermendez/bot-whatsapp#38]
Hola, he ejecutado el código tal y como viene de la rama Master, **ha funcionado!**
Lo único que no llego a entender, es por que no guarda la sessión, he puesto un console log y me da el resultado de `undefined`.
app.js -> linea 180
 ` client.on('authenticated', (session) => {
        sessionData = session;
        console.log('DATOS SESION: ' + sessionData);
        if(sessionData){
            fs.writeFile(SESSION_FILE_PATH, JSON.stringify(session), function (err) {
                if (err) {
                    console.log("Ocurrio un error con el archivo: ", err);
                }
            });
        }
    });`

¿Cúal puede ser el error? ¿Que no estoy viendo?

**Comment by Amariloco** [comment]
Esta raro, yo tengo error de al tener multidevice activo no guarda la sesión

**Comment by leifermendez** [comment]
Hola, al tener la version MultiDevice se deshabilita el guardar sesión. Se tendra que escanear nuevamente el QR espero pronto se pueda implementar alguna estrategia para mantener la session guardada
