### ISSUE TITLE
Escaneo codigo qr y me salta error

### ISSUE THREAD

**Issue by facu-rai** [leifermendez/bot-whatsapp#40]
[CHANGELOG.md](https://github.com/leifermendez/bot-whatsapp/files/8372697/CHANGELOG.md)
[README.md](https://github.com/leifermendez/bot-whatsapp/files/8372698/README.md)
vos me diras leifer, gracias

**Comment by hunimato** [comment]
Si esto no es suficiente corre los pasos anteriores y haz lo siguiente.

borra la carpeta **.bin** de **node_modules** y package.Lock.json y corre un **npm install** luego de hacerlo

Saludos,

Hugo
