### ISSUE TITLE
Hola Leifer Dialogflow error

### ISSUE THREAD

**Issue by satara2358** [leifermendez/bot-whatsapp#41]
Versión de "whatsapp-web.js": "^1.16.5" Actualizada
Ahora se perdió la comunicación con el servicio de Google. Genere una nueva chatbot-account pero igual, no se si deba actualizar también los módulos.

**Comment by hunimato** [comment]
Si esto no es suficiente corre los pasos anteriores y haz lo siguiente.

borra la carpeta .bin de node_modules y package.Lock.json y corre un npm install luego de hacerlo

Saludos,

Hugo

**Comment by satara2358** [comment]
Perfecto .... 
Gracias hunimato

**Comment by leifermendez** [comment]
Dejame saber si todo va bien! en el transcurso del día subo update
