### ISSUE TITLE
Obtener mensajes enviados

### ISSUE THREAD

**Issue by eabdala** [leifermendez/bot-whatsapp#43]
Estimado buenas, se puede interceptar los mensajes que envio ? no solo los que me llegan si no los que puedo enviar a mano.

**Comment by leifermendez** [comment]
HOla @eabdala claro lo puedes hacer aqui en la funcion sendMessage https://github.com/leifermendez/bot-whatsapp/blob/3ddbf462a8c8b0b3c07c4ffd2197331bef1ab77a/controllers/send.js#L46

**Comment by linaortiz9** [comment]
> HOla @eabdala claro lo puedes hacer aqui en la funcion sendMessage https://github.com/leifermendez/bot-whatsapp/blob/3ddbf462a8c8b0b3c07c4ffd2197331bef1ab77a/controllers/send.js#L46

Hola, si puedes hacer un ejemplo estaría bueno, puse el número y no envía los mensajes y intenté con el @.....y nada no envía los mensajes

**Comment by jasp402** [comment]
Yo tambien tengo la misma pregunta. **sendMessage** solo permite interceptar los mensajes que se envia desde la aplicacion pero no intercepta los que se envian desde el mobil. Desearia poder escuchar los mensajes que me envio a mi mismo.
