### ISSUE TITLE
Ayuda con DialogFlow y el bot

### ISSUE THREAD

**Issue by mcasa1** [leifermendez/bot-whatsapp#44]
Ya conecte el bot al dialogflow exitosamente y todo funciona perfecto mi problema es que yo quiero hacer que a partir de determinado mensaje se despliegue un Intent el cual le hace una serie de preguntas a traves de Actions and Parameters al usuario y esos datos los vaya almacenando para luego exportarlos a un spreadsheets. Tengo todo armado, cuando pruebo el intent en DialogFlow anda perfecto pero cuando conecto el bot y el Intent comienza a desplegarse, es decir hace la primer pregunta, al contestar el usuario por ejemplo su nombre, el bot en vez de seguir con el intent que ya comenzó y los parametros q le siguen, corre el intent que tiene como default cuando no reconoce lo que se le esta contestando, por ende imagino que el problema vendra desde la adaptacion del codigo ya que en el dialogflow todo corre perfecto. Si alguien pudiera ayudarme con esto seria genial. Gracias

**Comment by hunimato** [comment]
es un tema de adaptacion del codigo, pero todavia no ha dado leifer con la tecla, yo en mi caso llevo unas semanas intentando hacer algo parecido pero no he podido realizar ningun avance

**Comment by aleeepp** [comment]
Excelente proyecto!, solo funciona con essentials o con cx tambien?. Voy a probar también a ver como funciona la integración

**Comment by mcasa1** [comment]
> 
Yo solo probe con essentials que es con lo que lo explicaba Leifer en sus videos.

**Comment by jzvi12** [comment]
Yo tambien estoy experimentando este problema con el código más reciente. Incluso, integre Facebook messenger con  Dialogflow y también funcionó correctamente, PERO cuando se hace a través del WhatsApp bot, solo jala 2 de 4 preguntas y las demás no las reconoce y jala el Fallback.

**Comment by jzvi12** [comment]
https://discord.com/channels/698610475432411196/1047022134221873212/1047022134221873212
