### ISSUE TITLE
Sesion Guardada

### ISSUE THREAD

**Issue by izelaya051290** [leifermendez/bot-whatsapp#48]
Antes que nada Leifer, sos un Crack, Maestro...!!! Te felicito por tu contenido creo que nos sirve de mucho a personas que venimos aprendiendo programacion y soluciones practicas.

Tengo una duda, estoy usando Multidivice=True, sin embargo al parar el servicio y volverlo a correr, me pide nuevamente que escanee el codigo y no queda la Sesion Guardada

Ayuda con lo anterior!

**Comment by HerlyOlivares** [comment]
Saludos Leifer, hay alguna solucion para esto?... Me pasa igual.

**Comment by leifermendez** [comment]
Buenas por el momento aun no! espero pronto salga update

**Comment by Gonzalito87** [comment]
Con la actualizacion de whatsapp-web.js 1.16.6 el inconveniente persiste

**Comment by leifermendez** [comment]
Esperemos próxima update
