### ISSUE TITLE
Error al usar api/send

### ISSUE THREAD

**Issue by HerlyOlivares** [leifermendez/bot-whatsapp#51]
Hola Leifer,saludos, de antemano te agradezco por el proyecto, esta excelente, tengo un error al tratar de usar la ruta api/send, al parecer tiene que ver con el client, pero no puedo dar con el, me podrias ayudar con esto por favor.

Te dejo el error que aparece en consola:

El server esta listo por el puerto 3000
/var/www/html/Node/bot-whatsapp/controllers/send.js:50
    client.sendMessage(number, message);
           ^

TypeError: Cannot read properties of null (reading 'sendMessage')
    at Timeout._onTimeout (/var/www/html/Node/bot-whatsapp/controllers/send.js:50:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

Node.js v17.9.0

Gracias, excelente tu trabajo, sigue asi....

**Comment by izelaya051290** [comment]
HOla Herly, estas mandando valores Null  a la funcion send Message

**Comment by gelbermoran** [comment]
> HOla Herly, estas mandando valores Null a la función send Message

Me puedes ayudar con la manera que llame a las variables, que debo utilizar para que funcione?

Este es el error que me aparece

(node:2801) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
    at cleanNumber (/home/chatbot/bot-whatsapp/controllers/handle.js:10:21)
    at Timeout._onTimeout (/home/chatbot/bot-whatsapp/controllers/send.js:48:14)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2801) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by HerlyOlivares** [comment]
Hola @ulisesvina , la única manera en que lo pude solucionar y no se si es la mejor, pero funciono para mi, fue pasar toda la función sendMessage al archivo app.js, así de esa manera creo el cliente y de esa manera creo el cliente y me aseguro de que no pasa vació al método sendMessage, pero importando el controlador send.js me daba el error, espero pueda ser de ayuda.

**Comment by joseserrano15** [comment]
Gracias por tu sugerencia @ulisesvina, si no es mucha molestia, podrías compartir como te quedo al app.js así como la ruta de api/send? Soy muy novato con nodejs y no se del todo como hacer las modificaciones que comentas.

**Comment by HerlyOlivares** [comment]
``Te muestro como quedo mi archivo app.js,claro yo he agregado otras cosas como vistas (administrador), BD (mongoDB) entre otros...
`const db = require('./database/db');
const express = require('express');
const dotenv = require('dotenv');
const routes = require('./routes');
const cors = require('cors');
const dashboardRoutes = require('./routes/dashboard');
//const apiRoutes = require('./routes/api');
const path = require('path');
const expressLayouts = require('express-ejs-layouts');
const cookieParser = require('cookie-parser');
const session = require('express-session');
const MongoStore = require('connect-mongo');
const passport = require('./lib/passport');
const flash = require('connect-flash');
const bodyParser = require('body-parser');
const middleware = require('./middlewares/Auth');
const client = require('./lib/whatsapp');
const { cleanNumber, saveHistorial } = require('./helpers/handle');
const { ApiRequest } = require('./requests/apiRequest');

db.connect();

dotenv.config({path:'.env'});

const app = express();

// habilitar body-parser
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));


//Archivos estaticos
app.use(express.static('public'));
app.use('/assets', express.static(__dirname + 'public/assets'));
app.use('/dashboard', express.static(__dirname + 'public/assets'));

//session
app.use(cookieParser());
app.use(session({
    secret: process.env.SECRET,
    key: process.env.KEY,
    resave: false,
    saveUninitialized:false,
    store: MongoStore.create({ mongoUrl: process.env.DB_CONNECTION})
}));

client.initialize();

//passport
app.use(passport.initialize());
app.use(passport.session());

// Alertas y flash messages
app.use(flash());

// Crear nuestro middleware
app.use((req, res, next) => {
    res.locals.mensajes = req.flash();
    next();
});

//uso de layouts deexpress
app.use(expressLayouts);
app.set('layout', './layouts/master')
//Manejador de plantillas
app.set('view engine', 'ejs');


//Ruta de api

app.post('/api/send', (req, res) => {
    const {message, token} = req.body;
    let number = req.body.number;
    number = cleanNumber(number);
    
    console.log(message, number,token);
    const to = `${number}`;

    sendMessage(to, message);

    res.status(200).json({status: 'Enviado!'});
});

const sendMessage = async (to, message) => {
    await client.sendMessage(to, message);
    
}

// Rutas publicas
app.use('/', routes);

//Rutas Dashboard
app.use('/dashboard', middleware.auth, dashboardRoutes);


//Vistas
app.set('views', path.join(__dirname, './views'));

app.listen(process.env.PORT, () => {
    console.log('El sevidor esta funcionando en el puerto '+process.env.PORT);
});`

**Comment by HerlyOlivares** [comment]
`const db = require('./database/db');
const express = require('express');
const dotenv = require('dotenv');
const routes = require('./routes');
const cors = require('cors');
const dashboardRoutes = require('./routes/dashboard');
//const apiRoutes = require('./routes/api');
const path = require('path');
const expressLayouts = require('express-ejs-layouts');
const cookieParser = require('cookie-parser');
const session = require('express-session');
const MongoStore = require('connect-mongo');
const passport = require('./lib/passport');
const flash = require('connect-flash');
const bodyParser = require('body-parser');
const middleware = require('./middlewares/Auth');
const client = require('./lib/whatsapp');
const { cleanNumber, saveHistorial } = require('./helpers/handle');
const { ApiRequest } = require('./requests/apiRequest');

db.connect();

dotenv.config({path:'.env'});

const app = express();

// habilitar body-parser
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));


//Archivos estaticos
app.use(express.static('public'));
app.use('/assets', express.static(__dirname + 'public/assets'));
app.use('/dashboard', express.static(__dirname + 'public/assets'));

//session
app.use(cookieParser());
app.use(session({
    secret: process.env.SECRET,
    key: process.env.KEY,
    resave: false,
    saveUninitialized:false,
    store: MongoStore.create({ mongoUrl: process.env.DB_CONNECTION})
}));

client.initialize();

//passport
app.use(passport.initialize());
app.use(passport.session());

// Alertas y flash messages
app.use(flash());

// Crear nuestro middleware
app.use((req, res, next) => {
    res.locals.mensajes = req.flash();
    next();
});

//uso de layouts deexpress
app.use(expressLayouts);
app.set('layout', './layouts/master')
//Manejador de plantillas
app.set('view engine', 'ejs');


//Ruta de api

app.post('/api/send', (req, res) => {
    const {message, token} = req.body;
    let number = req.body.number;
    number = cleanNumber(number);
    
    console.log(message, number,token);
    const to = `${number}`;

    sendMessage(to, message);

    res.status(200).json({status: 'Enviado!'});
});

const sendMessage = async (to, message) => {
    await client.sendMessage(to, message);
    
}

// Rutas publicas
app.use('/', routes);

//Rutas Dashboard
app.use('/dashboard', middleware.auth, dashboardRoutes);


//Vistas
app.set('views', path.join(__dirname, './views'));

app.listen(process.env.PORT, () => {
    console.log('El sevidor esta funcionando en el puerto '+process.env.PORT);
});`

**Comment by joseserrano15** [comment]
@HerlyOlivares Mil gracias, ya funciona perfectamente. Saludos

**Comment by HerlyOlivares** [comment]
Un gusto @joseserrano15
