### ISSUE TITLE
Recibido de emoticons

### ISSUE THREAD

**Issue by Jhonzeroz** [leifermendez/bot-whatsapp#56]
Que tal, cuando me envían un emojis, el proceso se para automaticamente, estoy usandolo con base de datos mysql.

**Comment by jmarianoh** [comment]
Hola!!! Puedes enviar una imagen del error para investigar un poco más.

**Comment by Jhonzeroz** [comment]
![error](https://user-images.githubusercontent.com/35602835/165759557-075637fc-8153-428a-bdee-49ec36e70a26.PNG)

Buen día, al momeno de envíar un sticker o un emoji me aparece el error que envío a continuación, agradecería la ayuda

**Comment by Jhonzeroz** [comment]
La solucion (Empanada) que hice, fue que le agregue la linea character.... y le quite la otra linea de "error, result", ya recibe las imagenes, sticker, pero cuando mandan un emoji, no lo guarda y tampoco frena la aplicación.

![error1](https://user-images.githubusercontent.com/35602835/165793193-b1e6b510-0f5a-47c6-ad1c-efdd5b463828.PNG)

**Comment by Jhonzeroz** [comment]
la base de datos, tablas y campos hay que crearla con "ENGINE=InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;"
El bot  esta configurado para hacerlo con UTF8_GENERAL_CI;
Lo que hay que hacer es venirse al archivo ConnectionConfig.js
Reemplazar el UTF8_GNERAL_CI por UTF8MB4_UNICODE_CI
Los campos de la tabla messages, hay que crearlos NOT NULL, ya que esta se crea en automatico con NULL
