### ISSUE TITLE
Ejecución de metodos GET y de POST recepción de API desde json externo!!

### ISSUE THREAD

**Issue by gbelot2003** [leifermendez/bot-whatsapp#6]
Leifer Mendez, un placer, recién veo tu videos, nuevamente el programa esta genial. 
Estoy viendo la posibilidad de aplicar en un paso, un método GET para sincronizar con una RESTApi y tener 
información sincronizada desde otra base de datos como mejora. 
Imagina el potencial, usando tu bot como intermediario de API's.... 
Imagino que todo viene ligado a los steps en response, veré si termino de engranar los inital con los verbos api y te mando un pull request luego,

Saludos!!!

**Comment by leifermendez** [comment]
Saludos @gbelot2003  ok cuando lo tengas me avisas para ver la nueva funcionaliad
