### ISSUE TITLE
TypeError: nanoid is not a function

### ISSUE THREAD

**Issue by nicolaasrodriguez3** [leifermendez/bot-whatsapp#68]
Cuando quiero usar el bot mediante dialogflow me tira este error en el archivo dialogflow.js linea 37

**Comment by ndevalais** [comment]
en la linea 3 del archivo dialogflow.js cambiar la siguiente linea:
`const {nanoid} = require('nanoid')`

**Comment by leifermendez** [comment]
Librería removida 🙌 arreglado
