### ISSUE TITLE
Creo que no conecta con Dialog flow y los datos de el archivo chatbot-account.json son pasados por alto

### ISSUE THREAD

**Issue by ezequielal39** [leifermendez/bot-whatsapp#79]
Hola no logro conectar con dialogflow . Seguí los pasos del video . Crear Agente. Cree la cuenta de proyecto le di accseso
 a la API. cree las intenciones , intenciones similares al diálogo común con el chatbot offline y otras diferentes. Descargue el archivo JSON y lo pegue en chatbot-account.json. Nunca tuve el error 7 Permission :denied (y eso que segui los pasos del video) y creo que el programa no me está leyendo el archivo chatbot-account.json como si lo pasara por alto pero no me dice nada . O sea el único error que veo es que me contesta el chatbot offline y no él el dialogflow. Uso la version 14 de node porque es la única que me permitió instalar todo. Gracias de antemano

este es mi archivo .env
######DATABASE: none, mysql, dialogflow

DEFAULT_MESSAGE=false
SAVE_MEDIA=true
PORT=3000
DATABASE=none
LANGUAGE=es
SQL_HOST=
SQL_USER=
SQL_PASS=
SQL_DATABASE=
KEEP_DIALOG_FLOW=True
MULTI_DEVICE=true

**Comment by JaviJam** [comment]
Que error se indica en el terminal luego de ejecutarlo?

**Comment by ezequielal39** [comment]
Esto aparece en la terminal Por ejemplo cuando digo "hola" me responde el chatbot comun o sea el que no es de dialogflow. Yo Grabe en dialogflow una respuesta al Hola. Tambien grave en dialogflow una respuesta a "sobre los pantalones" y "precio de los pantalones". Pero no Hay respuesta


Ver QR http://localhost:3000/qr
Listo para escuchas mensajes
Client is ready!
🔴 escribe: hola
BODY hola
Saved
https://media2.giphy.com/media/VQJu0IeULuAmCwf5SL/giphy.gif
⚡⚡⚡ Enviando mensajes....
Saved
⚡⚡⚡ Enviando mensajes....
BODY sobre los pantalones
Saved
BODY precio de los pantalones
Saved

**Comment by JaviJam** [comment]
Pero si te responde lo que tienes en los archivos json, debes cambiar en el .ENV el origen de las respuestas.

**Comment by ezequielal39** [comment]
Hola y muchas gracias por tu ayuda, al parecer ahora quiere conectar , pero nose que significa este codigo de error
Configuración de .env

######DATABASE: none, mysql, dialogflow

DEFAULT_MESSAGE=false
SAVE_MEDIA=true
PORT=3000
DATABASE=dialogflow
LANGUAGE=es
SQL_HOST=
SQL_USER=
SQL_PASS=
SQL_DATABASE=
KEEP_DIALOG_FLOW=true
MULTI_DEVICE=true


TERMINAL:
Ver QR http://localhost:3000/qr
Listo para escuchas mensajes
Client is ready!
🔴 escribe: hola
BODY hola
Saved
(node:13372) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'payload' of undefined
    at detectIntent (C:\Users\ezequielal\Desktop\CHATBOT\bot-whatsapp-main\adapter\diaglogflow.js:59:39)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 
To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:13372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Gonzalito87** [comment]
incidencia duplicada con https://github.com/leifermendez/bot-whatsapp/issues/60; el codigo se resuelve comentando la cons ubicada en la linea 59  "const customPayload = parsePayload['payload']"

**Comment by leifermendez** [comment]
Gracias @Gonzalito87 revisar issue #60

**Comment by ezequielal39** [comment]
Muchas Gracias JaviJam, Gonzalito87 y liefermendez. Funciona Perfecto luego de comentar la línea 59 de dialogflow.js.
