### ISSUE TITLE
Error en /api/send

### ISSUE THREAD

**Issue by NRotili** [leifermendez/bot-whatsapp#8]
Hola Leifer, cómo estás? Mi nombre es Nicolás y te agradezco una vez más por tus grandiosos videos y repos. 

Estoy teniendo un error al enviar desde postman a https://localhost:3000/api/send mediante POST.

 `
(node:6428) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
    at cleanNumber (C:\xampp\htdocs\bot-whatsapp\controllers\handle.js:8:21)
    at Timeout._onTimeout (C:\xampp\htdocs\bot-whatsapp\controllers\send.js:31:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Sin embargo, la respuesta desde la API es "Enviado!"

Qué puede estar ocurriendo?

Gracias de antemano!

**Comment by leifermendez** [comment]
@NRotili lo reviso pero una idea para debugear es en esta linea de este archivo "controllers\send.js:31" igual en un rato que tenga un tiempo lo reviso

**Comment by leifermendez** [comment]
![image](https://user-images.githubusercontent.com/15802366/154993525-8435258f-bb63-46bd-b03d-7635a113af84.png)
Revisa que estes enviando los datos de la siguiente manera

**Comment by NRotili** [comment]
Error mío, estaba pasando los datos como x-www-form-urencoded. 
Un éxito funcionando con raw.
**Gracias Leifer por tanto.**

**Comment by untakereduardo** [comment]
Ante todo muchas gracias. Estoy teniendo un problema parecido. Me arroja un error en Controller->Send.js->sendMessage linea 50 me indica que client es nulo. A que se debe?  
![image](https://user-images.githubusercontent.com/33068510/167510089-e605194c-96c0-4f33-9f37-1f907776911f.png)
