### ISSUE TITLE
No se muestran los botones / menu  => Han podido resolverlo? 

### ISSUE THREAD

**Issue by innodicode** [leifermendez/bot-whatsapp#80]
Hola! he llegado a realizar varias instalaciones, con el objetivo de identicar algún tipo de error, lamentablemente, no se muestran los bótones. 

De casualidad, ustedes han tenido esta experiencia y han encontrado como solucionarlo?

**Comment by leifermendez** [comment]
Buenas los botones por el momento no funcionan estamos esperando que actualizen la libreria
