### ISSUE TITLE
me da un error al correr el programa

### ISSUE THREAD

**Issue by Charls1235** [leifermendez/bot-whatsapp#84]
segui las instrucciones como viene pero cuando corro el proyecto me manda estos errores y lo unico que hice fue cambiar los mensajes del initial y response json 

![image](https://user-images.githubusercontent.com/94659189/183768665-1af98a1b-5a91-43ab-89a2-731e2a61268d.png)
ese es el error que manda

**Comment by leifermendez** [comment]
Esta issue la cerrare por inactividad si tienen un problema no duden en re-abirla
