### ISSUE TITLE
Realizo el deploy en heroku y no corre

### ISSUE THREAD

**Issue by yonaiker95** [leifermendez/bot-whatsapp#85]
Al momento de realizar el desploy en heroku se instala perfectamente pero al corre me dice en el log una avertencia de que me falta el archivo .env y al solicitar el qr se reinicia la aplicacion. quisier saber como puedo solucionar esos problemas

**Comment by JaviJam** [comment]
Buenas Buenas,

SI no tienes el archivo .env, deberías duplicar el que se llama ".env.example" cambiando su nombre a ".env"

**Comment by yonaiker95** [comment]
![image](https://user-images.githubusercontent.com/39080439/184009267-67e36710-f8d5-436b-acbb-125d87374f9b.png)
trato de realizar el deploy de la nueva version pero falla el npm en heroku

**Comment by yonaiker95** [comment]
> Buenas Buenas,
> 
> SI no tienes el archivo .env, deberías duplicar el que se llama ".env.example" cambiando su nombre a ".env"


![image](https://user-images.githubusercontent.com/39080439/184279232-372641d6-a7d7-4386-b767-c596e992986b.png)

trato de realizar el deploy de la nueva version pero falla el npm en heroku
