### ISSUE TITLE
me marca error cuando pruebo el programa

### ISSUE THREAD

**Issue by Charls1235** [leifermendez/bot-whatsapp#86]
Estoy siguiendo las instruciiones para poder probar el programa pero me marca un error en la consola 

![image](https://user-images.githubusercontent.com/94659189/183935728-c1857f34-ddac-4279-83fd-82309208bc55.png)
ese es el error que marca segui las instrucciones deprimero npm intall y luego el archivo env pero me manda este error cuando corro el archivo

**Comment by jose2889** [comment]
Tuve el mismo error y se debe a que la importación de módulos de ese paquete **nodeid** cambio a partir de la versión 4.0.0. La solución por ahora que recomiendo es bajar a la versión anterior con el siguiente comando **npm i nanoid@3.3.4**

**Comment by leifermendez** [comment]
Este problema ya se soluciono, puedes volver a clonarte el proyecto para tener el código más reciente
