### ISSUE TITLE
error en "nanoid"

### ISSUE THREAD

**Issue by yonaiker95** [leifermendez/bot-whatsapp#87]
al momento de ingresar node app.js trata de iniciar el bot y me da error en nanoid const { nanoid } = require('nanoid').
solo ingrese npm install y luego inicie la app.

![image](https://user-images.githubusercontent.com/39080439/184561461-4ee9a06d-26a8-4988-9f01-863d0417d8a2.png)

**Comment by JhonyWalker1** [comment]
tengo el mismo problema

**Comment by jose2889** [comment]
@JhonyWalker1 te recomiento instalar la version anterior de nanoid npm i nanoid@3.3.4 ya que la 4.0.0 esta rompiendo el codigo.

**Comment by yonaiker95** [comment]
ya modifique el codigo y funciona perfectamente

> @JhonyWalker1 te recomiento instalar la version anterior de nanoid npm i nanoid@3.3.4 ya que la 4.0.0 esta rompiendo el codigo.

**Comment by yonaiker95** [comment]
@jose2889 aunque se repara el problema de nanoid sigue dando problema.

![image](https://user-images.githubusercontent.com/39080439/185263341-5cfea9ff-3e7a-421f-8dc6-3a5cebad0afd.png)

**Comment by JhonyWalker1** [comment]
Bro comenta esa linea y queda listo

**Comment by yonaiker95** [comment]
@JhonyWalker1 igual sigue sin poder realizar el deploy en heroku

**Comment by jose2889** [comment]
@yonaiker95 @JhonyWalker1 les recomiendo entren al grupo de discord que fue creado con este tema, van a encontrar mas informacion sobre los diferentes problemas que hemos estado presentando y pueden consultar sobre los errores ya que por aqui no veo que nadie pueda ayudarnos.

**Comment by JhonyWalker1** [comment]
Eso es cierto, no levanta en heroku .... @jose2889 me proporcionas el link de discord? gracias

**Comment by jose2889** [comment]
@JhonyWalker1 https://discord.com/invite/WzvtpeUFXh
