### ISSUE TITLE
Botónes del mensaje por defecto no funcionan

### ISSUE THREAD

**Issue by Atheror** [leifermendez/bot-whatsapp#9]
Saludos Leifer,
Me animaste a aprender NodeJS.

Encuentro un problema en la versión actual, cuando se manejan los botones de repuesta por JSON.

1. las respuestas se convierten a minúsculas por lo que no las recibe correctamente. Sería necesario actualizar las keywords en initial.json.
2. al enviar el enlace de youtube y telegram como "media", intenta descargarse y se termina la aplicación. Solucionado pasando los enlaces como parte de replyMessage.

**Comment by leifermendez** [comment]
Buenas puedes intentar actualizar el proyecto, volver a clonarlo ya se soluciono
