### ISSUE TITLE
Al intentar realizar el deploy en heroku da error

### ISSUE THREAD

**Issue by yonaiker95** [leifermendez/bot-whatsapp#90]
no puedo realizar el deploy en heroku alguna ayuda de como realizarlo?

![image](https://user-images.githubusercontent.com/39080439/185265918-337da2f6-c1ca-451c-a058-de0b2b8ed1ea.png)

**Comment by jose2889** [comment]
@yonaiker95 tuve el mismo error y el problema es porque las versiones de los paquetes que tienes en el archivo package.json no es la misma que tienes en el archivo package-lock.json lo que te recomiendo es eliminar package-lock.json ya que ese archivo se genera automaticamente cuando inicias la aplicacion y lo va hacer segun las versiones que tengas en el package.json.

espero que pueda haberme explicado, yo tengo actualmente un problema para deploy en heroku pero es un error diferente al tuyo, te lo muestro por si te ha pasado o te llega a pasar:

![image](https://user-images.githubusercontent.com/32442128/185525384-88b5a3b6-8577-4457-94fd-6bf89baf808b.png)
