### ISSUE TITLE
SESSION_FILE_PATH is not defined

### ISSUE THREAD

**Issue by franDelfinCh** [leifermendez/bot-whatsapp#96]
![image](https://user-images.githubusercontent.com/105655651/187731425-955fd6c8-7804-4432-baea-cf83c5ab4c44.png)

- me podran ayudar con este error por fabor 
- el codigo 
![image](https://user-images.githubusercontent.com/105655651/187731869-9288fc71-3607-4db2-b428-9987c7a52857.png)

**Comment by leifermendez** [comment]
@franDelfinCh la version del web-whatsapp ya se ha actualizado ahora ya se implementa de manera diferente el guardar session. Todo ese codigo ya se actualizo te recomiendo clonar el proyecto nuevamente
