### ISSUE TITLE
Botones y DialogFlow por el payload. No funciona

### ISSUE THREAD

**Issue by HKong31** [leifermendez/bot-whatsapp#99]
Mientras esto funciona a través del payload (aunque a vcs la imagen sale primero que el mensaje):
{
"media":"https://media2.giphy.com/media/VQJu0IeULuAmCwf5SL/giphy.gif",
}
Esto no funciona casi de ninguna forma de las que he probado (colocándolo en el payload):
{
        "actions":{
            "title":"¿Que te interesa ver?",
            "message":"Recuerda todo este contenido es gratis y estaria genial que me siguas!",
            "footer":"Gracias",
            "buttons":[
                {"body":"Cursos"},
                {"body":"Youtube"},
                {"body":"Telegram"}
            ]
        }
}

Si alguien sabe como lograr esto....

**Comment by KJoaquin** [comment]
Para los botones corre este comando para moverte a la rama resuelta del api de whatsapp

`npm i github:pedroslopez/whatsapp-web.js#fix-buttons-list`

Con respecto a DialogFlow, cual es tu problema?

**Comment by KJoaquin** [comment]
Listo ya comprendo:

![Captura de Pantalla 2022-09-20 a la(s) 11 39 35](https://user-images.githubusercontent.com/29418222/191326865-38110fe4-1178-4a62-97e4-5522025fa6cf.png)

En el caso de que lo quieras agregar asi, tienes que agregar al código la función, ya que no se encuentra esa función asi

**adapter/dialogflow.js**

![Captura de Pantalla 2022-09-20 a la(s) 11 42 01](https://user-images.githubusercontent.com/29418222/191327304-b6aa08dc-c9cb-432f-b8fc-3a4ded58bfff.png)

La función tendría que leerse e interpretarse para que envie la estructura en la función de envio de botones, esto se tendría que agregar  desde:

**controllers/flow.js**

![Captura de Pantalla 2022-09-20 a la(s) 11 45 27](https://user-images.githubusercontent.com/29418222/191328000-bde65063-14fd-42b2-9538-75d0a0382437.png)

La otra opción seria que lo agregues directamente en el **app.js**

![Captura de Pantalla 2022-09-20 a la(s) 11 46 33](https://user-images.githubusercontent.com/29418222/191328194-236bfb25-cc00-46a5-90bd-12a03dbb2b1d.png)

En dado caso que no lo quieras agregar de esta manera y quieras jugar mas con los **Intets** puedes hacerlo de esta manera:

![Captura de Pantalla 2022-09-20 a la(s) 11 48 45](https://user-images.githubusercontent.com/29418222/191328599-6fbd6964-0c29-4ea3-ae1b-cbee06230e60.png)

De esta manera puedes jugar con todas las funciones que incluye el api.



Espero ser de ayuda, quedo atento a tus comentarios

**Comment by HKong31** [comment]
Excelente, muchísimas gracias por taimarte el tiempo. Tan pronto puedo me pongo a trabajar. De verdad repito, agradecido.

**Comment by KJoaquin** [comment]
Lograste @HKong31 ??

**Comment by HKong31** [comment]
Hola @KJoaquin, Nope, aun no (por favor, ten en cuenta que no soy coder aun, ando aprendiendo). sin embargo, logre que en lugar de darme este output:
```javascript
actions: { structValue: { fields: [Object] }, kind: 'structValue' }
```
Me diera este:
```javascript
{
  buttons: [ { body: 'Cursos' }, { body: 'Youtube' }, { body: 'Telegram' } ],
  title: '¿Que te interesa ver?',
  footer: 'Gracias',
  message: 'Recuerda todo este contenido es gratis y estaria genial que me siguas!'
}
```
No se si es la vía o no, pero hice un decode del payload que recibo de DialogFlow de ese Object. Y alli estoy estancado en este momento.

**Comment by HKong31** [comment]
NVM, ya logre hacerlos funcionar. Lo que pasa ahora es que si en el payload no hay un `"media": "xxxx.jpg"` me tira un error:
```
/home/xxxxxxxxx/botxxxx/pruebaxxxx/bot-whatsapp/adapter/diaglogflow.js:61
        media = fields.media.stringValue || null
                             ^

TypeError: Cannot read properties of undefined (reading 'stringValue')
    at detectIntent (/home/xxxxxxxxxx/botxxxx/pruebaxxxxx/bot-whatsapp/adapter/diaglogflow.js:61:30)
```

Pero ya estoy cansando, lo veo luego.

**Comment by KJoaquin** [comment]
Yo lo tengo de esta manera

![Captura de pantalla 2022-11-02 a la(s) 10 13 27 a  m](https://user-images.githubusercontent.com/29418222/199542636-ecaee3c8-75db-428d-b616-724df851bdcd.png)

Pero tambien lo tienes que validar en el flows.js

![Captura de pantalla 2022-11-02 a la(s) 10 13 56 a  m](https://user-images.githubusercontent.com/29418222/199542763-897f9c7b-7c9f-4016-9413-80100948b5ba.png)
